jwt:
  secret: ThisIsAVeryLongSecretKeyThatIsAtLeastSixtyFourBytesLongForTheHS512Algorithm
  expiration: 86400000

spring:
  cache:
    type: caffeine
    caffeine:
      spec: expireAfterWrite=10m
  datasource:
    url: jdbc:postgresql://34.122.24.32:5432/TestDB
    username: postgres
    password: postgres
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
logging:
  file:
        path: /src/
        name: fileloging

  level:
    com.example.fiegerunner.controller.ImportController: INFO
    root: INFO