
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: зщыепкуы
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
logging:
  file:
        path: /src/
        name: fileloging

  level:
    com.example.fiegerunner.controller.ImportController: INFO
    root: WARN